In [ ]:
#importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [ ]:
df = pd.read_csv('indian_liver_patient.csv')
df.head()

Age  Gender  Total_Bilirubin  ...  Albumin  Albumin_and_Globulin_Ratio  Dataset
0   65  Female              0.7  ...      3.3                        0.90        1
1   62    Male             10.9  ...      3.2                        0.74        1
2   62    Male              7.3  ...      3.3                        0.89        1
3   58    Male              1.0  ...      3.4                        1.00        1
4   72    Male              3.9  ...      2.4                        0.40        1

[5 rows x 11 columns]

In [ ]:
df.describe()

Age  Total_Bilirubin  ...  Albumin_and_Globulin_Ratio     Dataset
count  583.000000       583.000000  ...                  579.000000  583.000000
mean    44.746141         3.298799  ...                    0.947064    1.286449
std     16.189833         6.209522  ...                    0.319592    0.452490
min      4.000000         0.400000  ...                    0.300000    1.000000
25%     33.000000         0.800000  ...                    0.700000    1.000000
50%     45.000000         1.000000  ...                    0.930000    1.000000
75%     58.000000         2.600000  ...                    1.100000    2.000000
max     90.000000        75.000000  ...                    2.800000    2.000000

[8 rows x 10 columns]

In [ ]:
df.isnull().any()

Age                           False
Gender                        False
Total_Bilirubin               False
Direct_Bilirubin              False
Alkaline_Phosphotase          False
Alamine_Aminotransferase      False
Aspartate_Aminotransferase    False
Total_Protiens                False
Albumin                       False
Albumin_and_Globulin_Ratio     True
Dataset                       False
dtype: bool

In [ ]:
#Filling null values with mean
df = df.fillna(df['Albumin_and_Globulin_Ratio'].mean())

In [ ]:
df.isnull().any()

Age                           False
Gender                        False
Total_Bilirubin               False
Direct_Bilirubin              False
Alkaline_Phosphotase          False
Alamine_Aminotransferase      False
Aspartate_Aminotransferase    False
Total_Protiens                False
Albumin                       False
Albumin_and_Globulin_Ratio    False
Dataset                       False
dtype: bool

In [ ]:
#features and labels
x = df.drop(columns = ('Dataset'))
y = df['Dataset']

In [ ]:
x = x.replace('Male', 0)
x = x.replace('Female',1)

In [ ]:
#Test train split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.1,random_state=30)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(524, 10)
(59, 10)
(524,)
(59,)


In [ ]:
#KNN MODEL
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [ ]:
#PREDICTIONS
y_pred = knn.predict(x_test)
y_pred

array([1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1, 2, 1, 1,
       1, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 2, 2,
       2, 1, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2])

In [ ]:
#ACCURACY
acc = accuracy_score(y_test,y_pred)
print("ACCURACY : ",acc*100,"%")

ACCURACY :  62.71186440677966 %


In [ ]:
#Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

In [ ]:
#Random forest predictions
rf.fit(x_train,y_train)
y_pred_1 = rf.predict(x_test)
y_pred_1

array([1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1])

In [ ]:
#Accuracy
acc = accuracy_score(y_test,y_pred_1)
print("ACCURACY : ",acc*100,"%")

ACCURACY :  79.66101694915254 %


In [ ]:
#Support Vector Machine
from sklearn.svm import SVC
svc = SVC()

In [ ]:
svc.fit(x_train,y_train)
y_pred_2 = svc.predict(x_test)
y_pred_2

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [ ]:
#Accuracy
acc = accuracy_score(y_test,y_pred_2)
print("ACCURACY : ",acc*100,"%")

ACCURACY :  74.57627118644068 %
